------------------------------------------------------------------
-- NEAR_DUP_QUEUE.sql  DB2 for z/OS DDL — MICPS-4471
-- Schema: MIVANCPS   Subsystem: DB2P
------------------------------------------------------------------
CREATE STOGROUP MIVANCPS_OVP_STG
  VOLUMES (MIVOVP1, MIVOVP2)
  VCAT MIVCAT;

CREATE TABLESPACE NDUPQTS
  IN MIVANCPS
  USING STOGROUP MIVANCPS_OVP_STG
  PRIQTY 720 SECQTY 72
  LOCKSIZE PAGE
  BUFFERPOOL BP2
  COMPRESS YES;

CREATE TABLE MIVANCPS.NEAR_DUP_QUEUE (
    NDUP_CLAIM_ID        CHAR(20)         NOT NULL,
    NDUP_ORIG_CLAIM_ID   CHAR(20)         NOT NULL,
    NDUP_MEMBER_ID       CHAR(15)         NOT NULL,
    NDUP_PROV_NPI        CHAR(10)         NOT NULL,
    NDUP_DOS             DECIMAL(8,0)     NOT NULL,
    NDUP_CPT_CD          CHAR(5)          NOT NULL,
    NDUP_CHARGE_AMT      DECIMAL(9,2)     NOT NULL,
    NDUP_MATCH_TYPE      CHAR(10)         NOT NULL,
    NDUP_PEND_REASON     CHAR(20)         NOT NULL DEFAULT 'NEAR-DUP-REVIEW',
    NDUP_CREATE_DT       DECIMAL(8,0)     NOT NULL,
    NDUP_STATUS          CHAR(1)          NOT NULL DEFAULT 'P',
    CONSTRAINT NDUPQ_PK  PRIMARY KEY (NDUP_CLAIM_ID),
    CONSTRAINT NDUPQ_FK1 FOREIGN KEY (NDUP_CLAIM_ID)
        REFERENCES MIVANCPS.CLAIM_PAYMENT (CLAIM_ID)
        ON DELETE RESTRICT,
    CONSTRAINT NDUPQ_CHK_STATUS
        CHECK (NDUP_STATUS IN ('P','A','D')),
    CONSTRAINT NDUPQ_CHK_MATCH
        CHECK (NDUP_MATCH_TYPE IN ('DATE-DRIFT','AMT-VAR','MODIFIER','COMBINED'))
) IN MIVANCPS.NDUPQTS;

-- Status + create-date cluster for batch sweep
CREATE INDEX MIVANCPS.NDUPQ_IX1
    ON MIVANCPS.NEAR_DUP_QUEUE (NDUP_STATUS ASC, NDUP_CREATE_DT ASC)
    CLUSTER;

-- Member + DOS for online lookup
CREATE INDEX MIVANCPS.NDUPQ_IX2
    ON MIVANCPS.NEAR_DUP_QUEUE (NDUP_MEMBER_ID, NDUP_DOS);

-- Pend reason for reporting
CREATE INDEX MIVANCPS.NDUPQ_IX3
    ON MIVANCPS.NEAR_DUP_QUEUE (NDUP_PEND_REASON, NDUP_STATUS);

GRANT SELECT, INSERT, UPDATE ON TABLE MIVANCPS.NEAR_DUP_QUEUE
    TO MICPS_BATCH;
GRANT SELECT ON TABLE MIVANCPS.NEAR_DUP_QUEUE
    TO MICPS_ONLINE;
GRANT SELECT ON TABLE MIVANCPS.NEAR_DUP_QUEUE
    TO MICPS_REPORT;