-- ====================================================================
-- MiCPS Provider Data Validation — dev schema (H2 / PostgreSQL mode)
-- Mirrors the DB2 tables referenced by the MPRVVLDR0 program tree.
-- ====================================================================

DROP TABLE IF EXISTS provider_sanction_log;
DROP TABLE IF EXISTS network_contract;
DROP TABLE IF EXISTS network_tier;
DROP TABLE IF EXISTS state_exclusion_list;
DROP TABLE IF EXISTS sam_exclusion_list;
DROP TABLE IF EXISTS oig_exclusion_list;
DROP TABLE IF EXISTS provider_credential;
DROP TABLE IF EXISTS provider_master;

-- PROVIDER_MASTER  (COBOL: MPRVMSTR / PROV-MSTR VSAM KSDS) ------------
CREATE TABLE provider_master (
    npi             VARCHAR(10)  NOT NULL PRIMARY KEY,
    npi_type        VARCHAR(1),
    tax_id          VARCHAR(9),
    last_name       VARCHAR(35),
    first_name      VARCHAR(25),
    org_name        VARCHAR(60),
    taxonomy_1      VARCHAR(10),
    taxonomy_2      VARCHAR(10),
    specialty_cd    VARCHAR(4),
    network_status  VARCHAR(3),
    contract_id     VARCHAR(15),
    network_tier    VARCHAR(2),
    cred_status     VARCHAR(2),
    cred_exp_dt     DATE,
    excl_flag       VARCHAR(1)   DEFAULT 'N',
    excl_dt         DATE,
    effective_dt    DATE,
    term_dt         DATE,
    status_cd       VARCHAR(2)
);

-- PROVIDER_CREDENTIAL  (COBOL: MPRVCRED) -----------------------------
CREATE TABLE provider_credential (
    cred_id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npi             VARCHAR(10)  NOT NULL,
    type_cd         VARCHAR(4),
    issuer          VARCHAR(40),
    number          VARCHAR(20),
    state           VARCHAR(2),
    issue_dt        DATE,
    expiry_dt       DATE,
    status_cd       VARCHAR(2),
    verified_dt     DATE,
    verified_by     VARCHAR(10),
    caqh_id         VARCHAR(10)
);

-- OIG_EXCLUSION_LIST  (COBOL: MPRVEXCL / MPRVEXC0) -------------------
CREATE TABLE oig_exclusion_list (
    excl_id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npi             VARCHAR(10),
    tax_id          VARCHAR(9),
    excl_type_cd    VARCHAR(4),
    effective_dt    DATE,
    reinstate_dt    DATE,
    reason_cd       VARCHAR(4)
);

-- SAM_EXCLUSION_LIST -------------------------------------------------
CREATE TABLE sam_exclusion_list (
    excl_id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npi             VARCHAR(10),
    tax_id          VARCHAR(9),
    excl_type_cd    VARCHAR(4),
    effective_dt    DATE,
    reinstate_dt    DATE,
    reason_cd       VARCHAR(4)
);

-- STATE_EXCLUSION_LIST -----------------------------------------------
CREATE TABLE state_exclusion_list (
    excl_id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npi             VARCHAR(10),
    tax_id          VARCHAR(9),
    state           VARCHAR(2),
    excl_type_cd    VARCHAR(4),
    effective_dt    DATE,
    reinstate_dt    DATE,
    reason_cd       VARCHAR(4)
);

-- NETWORK_CONTRACT  (COBOL: MPRVNETW / MPRVNET0) --------------------
CREATE TABLE network_contract (
    contract_pk     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npi             VARCHAR(10)  NOT NULL,
    contract_id     VARCHAR(15),
    network_id      VARCHAR(10),
    tier_cd         VARCHAR(2),
    fee_sched_id    VARCHAR(10),
    effective_dt    DATE,
    term_dt         DATE,
    status_cd       VARCHAR(2),
    accept_new_pat  VARCHAR(1)
);

-- NETWORK_TIER -------------------------------------------------------
CREATE TABLE network_tier (
    tier_cd         VARCHAR(2)   NOT NULL PRIMARY KEY,
    tier_name       VARCHAR(30),
    tier_rank       INTEGER,
    description     VARCHAR(100)
);

-- PROVIDER_SANCTION_LOG  (COBOL: MPRVSANL0) -------------------------
CREATE TABLE provider_sanction_log (
    log_id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npi             VARCHAR(10)  NOT NULL,
    event_cd        VARCHAR(4),
    valid_flag      VARCHAR(1),
    excl_flag       VARCHAR(1),
    deny_reason     VARCHAR(30),
    network_ind     VARCHAR(3),
    tier_cd         VARCHAR(2),
    log_ts          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- Seed data for local shadow-mode testing
-- ====================================================================
INSERT INTO provider_master
    (npi, npi_type, tax_id, last_name, first_name, org_name,
     taxonomy_1, specialty_cd, network_status, contract_id,
     network_tier, cred_status, cred_exp_dt, excl_flag,
     effective_dt, term_dt, status_cd)
VALUES
    ('1234567893','1','123456789','SMITH','JOHN','',
     '207Q00000X','0100','INN','CNTR0001',
     'T1','AC', DATE '2027-06-30','N',
     DATE '2020-01-01', NULL,'AC'),
    ('1987654320','1','987654321','JONES','MARY','',
     '208D00000X','0200','OON','',
     'T2','AC', DATE '2026-12-31','N',
     DATE '2019-03-15', NULL,'AC'),
    ('1122334455','2','223344556','','','MERCY CLINIC LLC',
     '261Q00000X','0300','INN','CNTR0099',
     'T1','AC', DATE '2027-01-31','Y',
     DATE '2018-07-01', NULL,'AC');

INSERT INTO provider_credential
    (npi, type_cd, issuer, number, state, issue_dt, expiry_dt,
     status_cd, verified_dt, verified_by, caqh_id)
VALUES
    ('1234567893','LIC','STATE MEDICAL BOARD','MD123456','NY',
     DATE '2020-01-01', DATE '2027-06-30','AC',
     DATE '2025-01-15','CRED001','CAQH00123'),
    ('1987654320','LIC','STATE MEDICAL BOARD','MD987654','NJ',
     DATE '2019-03-15', DATE '2026-12-31','AC',
     DATE '2025-02-20','CRED001','CAQH00456');

INSERT INTO oig_exclusion_list
    (npi, tax_id, excl_type_cd, effective_dt, reinstate_dt, reason_cd)
VALUES
    ('1122334455','223344556','1128','2023-05-01', NULL,'FRUD');

INSERT INTO network_contract
    (npi, contract_id, network_id, tier_cd, fee_sched_id,
     effective_dt, term_dt, status_cd, accept_new_pat)
VALUES
    ('1234567893','CNTR0001','NET-COMM','T1','FS-COMM-01',
     DATE '2020-01-01', NULL,'AC','Y');

INSERT INTO network_tier (tier_cd, tier_name, tier_rank, description)
VALUES
    ('T1','PREFERRED',1,'Tier 1 preferred network'),
    ('T2','STANDARD',2,'Tier 2 standard network'),
    ('T3','OUT-OF-NETWORK',9,'Non-participating');
